### João Vitor Chaves de Oliveira <br>
### Professor Hélio Cortes

In [140]:
import numpy as np
from numpy.linalg import inv
import copy as copy
np.set_printoptions(suppress=True)
import math

## Questão 1 a.

Seja $A_{a,b,n} \in \mathbb{R}^{nxn}$ a matriz tridiagonal dada por:

$
A = \left[
\begin{array}{ccccccc}
a & b & 0 & ... & 0 & 0 \\
b & a & b &  0 & \ddots & \vdots \\
0   & b & a & b & \ddots & \vdots \\
\vdots   & \ddots & \ddots & \ddots & \ddots & 0 \\
\vdots   & \ddots & 0 & b & a & b \\
0   & ... & ... & 0 & b & a \\
\end{array}
\right]_{nxn}
$

Faça um algoritmo para obter uma decomposição Cholesky de uma matriz tridiagonal $A_{a,b,n}$, supondo que ela seja definida positiva.

In [141]:
def is_simetric(matrix):
    n = len(matrix)
    for i in range(n):
        for j in range(i,n):
            if i != j :
                if matrix[i][j] != matrix[j][i]:
                    return False
    return True

def is_defined_positive(matrix):
    eigvalues = np.linalg.eigvals(matrix)
    for i in eigvalues:
        if(not np.isreal(i)):
            return False
    return min(eigvalues)>0


def Cholesky_Tridiagonal(A):
    if is_simetric(A) and is_defined_positive(A):
        
        L = copy.deepcopy(A)
        n = len(A)
        for i in range(n-1):
            L[i][i] = L[i][i]**(1/2)
            L[i+1][i] = L[i+1][i]/L[i][i]
            L[i+1][i+1] = L[i+1][i+1] - L[i+1][i]**(2)  
        L[n-1][n-1] = L[n-1][n-1]**(1/2)
        
        for i in range(n):
            for j in range(i+1,n):
                L[i][j] = 0
        return L
    else:
        return "Não é simétrica ou não é definida positiva"

In [142]:
A = [[5,1,0,0],[1,5,1,0],[0,1,5,1],[0,0,1,5]]
B = [[2, 1,0,0,0], [1,2,1,0,0], [0,1,2,1,0],[0,0,1,2,1],[0,0,0,1,2]]

In [143]:
Cholesky_Tridiagonal(A)

[[2.23606797749979, 0, 0, 0],
 [0.4472135954999579, 2.1908902300206643, 0, 0],
 [0, 0.45643546458763845, 2.188987589427283, 0],
 [0, 0, 0.45683219257612856, 2.188904828407596]]

In [144]:
np.linalg.cholesky(A)

array([[2.23606798, 0.        , 0.        , 0.        ],
       [0.4472136 , 2.19089023, 0.        , 0.        ],
       [0.        , 0.45643546, 2.18898759, 0.        ],
       [0.        , 0.        , 0.45683219, 2.18890483]])

In [145]:
Cholesky_Tridiagonal(B)

[[1.4142135623730951, 0, 0, 0, 0],
 [0.7071067811865475, 1.224744871391589, 0, 0, 0],
 [0, 0.8164965809277261, 1.1547005383792515, 0, 0],
 [0, 0, 0.8660254037844387, 1.118033988749895, 0],
 [0, 0, 0, 0.8944271909999159, 1.0954451150103324]]

In [146]:
np.linalg.cholesky(B)

array([[1.41421356, 0.        , 0.        , 0.        , 0.        ],
       [0.70710678, 1.22474487, 0.        , 0.        , 0.        ],
       [0.        , 0.81649658, 1.15470054, 0.        , 0.        ],
       [0.        , 0.        , 0.8660254 , 1.11803399, 0.        ],
       [0.        , 0.        , 0.        , 0.89442719, 1.09544512]])

## Questão 1 b.

Faça um algoritmo para obter uma decomposição QR de uma matriz tridiagonal $A_{a,b,n}$. Escolha entre Gram-Schmidt, Householder e Givens, a que melhor se aplica nesse contexto.

In [147]:
def givens(A):
    k = 0
    n = len(A)
    R = copy.deepcopy(A)
    Q = np.identity(n)
    for i in range(n-1):
        a = R[i][i]
        b = R[i+1][i]
        r = np.sqrt(np.power(a,2) + np.power(b,2))
        c = a/float(r)
        s = -b/float(r)
        Qk = np.identity(n)
        Qk[i][i] = c
        Qk[i+1][i] = s
        Qk[i][i+1] = -s
        Qk[i+1][i+1] = c
        if(k==0):
            k=1
            Q = Qk
            R = np.matmul(Qk,R)
        else:
            
            Q = np.matmul(Qk,Q)
            R = np.matmul(Qk,R)
    return R,Q.T

In [148]:
R,Q = givens(B)
print("**********  R  ******************")
print(R)
print("**********  Q  ******************")
print(Q)
print("**********  QR  ******************")
print(np.dot(Q,R))

**********  R  ******************
[[ 2.23606798  1.78885438  0.4472136   0.          0.        ]
 [ 0.          1.67332005  1.91236577  0.5976143   0.        ]
 [ 0.          0.          1.46385011  1.95180015  0.68313005]
 [ 0.         -0.          0.          1.3540064   1.96946386]
 [ 0.          0.         -0.          0.          0.80903983]]
**********  Q  ******************
[[ 0.89442719 -0.35856858  0.19518001 -0.12309149  0.13483997]
 [ 0.4472136   0.71713717 -0.39036003  0.24618298 -0.26967994]
 [ 0.          0.5976143   0.58554004 -0.36927447  0.40451992]
 [ 0.          0.          0.68313005  0.49236596 -0.53935989]
 [ 0.          0.          0.          0.73854895  0.67419986]]
**********  QR  ******************
[[ 2.  1. -0.  0.  0.]
 [ 1.  2.  1. -0. -0.]
 [ 0.  1.  2.  1.  0.]
 [ 0.  0.  1.  2.  1.]
 [ 0.  0. -0.  1.  2.]]


## Questão 3

Determine uma base ortonormal para o espaço complementar ortogonal ao vetor $v = [1,-1,1] \in \mathbb{R}^{3}.$

In [233]:
def norma(v):
    return np.sqrt(v[0]**2+v[1]**2+v[2]**2)

    
def ComplementoOrtonormal(v):
    x,y,z = v
    if x == 0 and y == 0 and z == 0:
        return np.matrix([0,0,0])
    
    if x != 0:
        v1 = np.array([-z/x,0,1])
        v2 = np.array([-y/x,1,0])
        w1 = v1
        w1v2 = np.dot(w1,v2)
        w1w1 = (w1[0]**2+w1[1]**2+w1[2]**2)
        w2 = v2 - (w1v2/w1w1)*w1
    
        nw1 = norma(w1)
        nw2 = norma(w2)
        return w1,w2
        
    
    elif y !=0:
        v1 = np.array([1,-x/y,0])
        v2 = np.array([0,-z/y,1])
        w1 = v1
        w1v2 = np.dot(w1,v2)
        w1w1 = (w1[0]**2+w1[1]**2+w1[2]**2)
        w2 = v2 - (w1v2/w1w1)*w1
    
        nw1 = norma(w1)
        nw2 = norma(w2)
        return w1,w2
        
        
    elif z != 0:
        v1 = np.array([1,0,x/z])
        v2 = np.array([0,1,-y/z])
        w1 = v1
        w1v2 = np.dot(w1,v2)
        w1w1 = (w1[0]**2+w1[1]**2+w1[2]**2)
        w2 = v2 - (w1v2/w1w1)*w1
    
        nw1 = norma(w1)
        nw2 = norma(w2)
        return w1,w2


In [243]:
v = np.array([1,-1,1])
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])
v3 = np.array([0,0,1])
v4 = np.array([1,1,0])
v5 = np.array([1,0,1])
v6 = np.array([1,1,1])
v7 = np.array([1,-1,1])

In [244]:
ComplementoOrtonormal(v1)

(array([0., 0., 1.]), array([0., 1., 0.]))

In [235]:
ComplementoOrtonormal(v2)

(array([1., 0., 0.]), array([0., 0., 1.]))

In [236]:
ComplementoOrtonormal(v3)

(array([1., 0., 0.]), array([0., 1., 0.]))

In [237]:
ComplementoOrtonormal(v4)

(array([0., 0., 1.]), array([-1.,  1.,  0.]))

In [238]:
ComplementoOrtonormal(v5)

(array([-1.,  0.,  1.]), array([0., 1., 0.]))

In [239]:
ComplementoOrtonormal(v6)

(array([-1.,  0.,  1.]), array([-0.5,  1. , -0.5]))

In [242]:
ComplementoOrtonormal(v7)

(array([-1.,  0.,  1.]), array([0.5, 1. , 0.5]))

## Questão 4

Suponha que uma matriz $A \in \mathbb{R}^{mxn}$ tenha posto máximo. A pseudoinversa, ou inversa de Moore-Penrose, de $A$ é a matriz $A^{+} \in \mathbb{R}^{nxm}$ que satisfaz:

<ul>
  <li>$AA^{+}A = A$</li>
  <li>$A^{+}AA^{+} = A^{+}$</li>
  <li>$(AA^{+})^{T} = AA^{+}$</li>
  <li>$(A^{+}A)^{T} = A^{+}A$</li>
</ul>

Calcule a pseudoinversa de

$
A = \left[
\begin{array}{cc}
1 & 0 \\
0 & 1 \\
0 & 1\\
\end{array}
\right]
$

In [149]:
#def VerifyProperties(A):
#    A_pseudo = Pseudoinverse(A)
#    cond1 = np.dot(np.dot(A,A_pseudo),A)                # AA+A  == A 
#    cond2 = np.dot(np.dot(A_pseudo,A),A_pseudo)         # A+AA+ == A+
#    
#    aux = np.dot(A,A_pseudo)                            # (AA+) == AA+ 
#    cond3 = aux.T
#    
#    aux2 = np.dot(A_pseudo,A)
#    cond4 = aux2.T                                      # (A+A) == A+A
#    
#    if np.matrix.all(cond1 == A):
#        if np.matrix.all(cond2 == A_pseudo):
#            if np.matrix.all(cond3 == np.dot(A,A_pseudo)):
#                if np.matrix.all(cond4 == np.dot(A_pseudo,A)):
#                    return True
#                else:
#                    print("Parou na condição 4")
#                    return False
#            else:
#                print("Parou na condição 3")
#                return False
#        else:
#            print("Parou na condição 2")
#            return False
#    else:
#        print("Parou na condição 1")
#        return False

In [150]:
def Pseudoinverse(A):
    At = np.transpose(A)
    AtA = np.dot(At,A)
    AtA_inv = np.linalg.inv(AtA)
    Pi = np.dot(AtA_inv,At)
    return Pi
    
    
A = np.matrix([[1,0],[0,1],[0,1]])
B = np.matrix([[2,-1,0],[4,3,-2]])

In [151]:
print(Pseudoinverse(A))
print("\n")
print(Pseudoinverse(B))

[[1.  0.  0. ]
 [0.  0.5 0.5]]


[[ 0.125  0.5  ]
 [-0.75   0.   ]
 [-1.     0.   ]]


In [152]:
C = np.matrix([[7,2],[3,4],[5,3]])
print(C)

[[7 2]
 [3 4]
 [5 3]]


In [153]:
Pseudoinverse(C)

matrix([[ 0.16666667, -0.10606061,  0.03030303],
        [-0.16666667,  0.28787879,  0.06060606]])

In [154]:
D = np.matrix([[2,-1,0],[4,3,-2]])

print(D)
cond1 = np.dot(np.dot(D,Pseudoinverse(D)),D) 
print(cond1)


[[ 2 -1  0]
 [ 4  3 -2]]
[[ 6.    2.   -2.  ]
 [ 8.5   5.75 -4.  ]]


In [155]:
Pseudoinverse(D)

matrix([[ 0.125,  0.5  ],
        [-0.75 ,  0.   ],
        [-1.   ,  0.   ]])

In [156]:
G = np.linalg.pinv(D)
print(G)

[[ 0.31666667  0.08333333]
 [-0.36666667  0.16666667]
 [ 0.08333333 -0.08333333]]
