In [1]:
import numpy as np
from numpy.linalg import inv
import copy as copy

## Questão 1 a.

Seja $A_{a,b,n} \in \mathbb{R}^{nxn}$ a matriz tridiagonal dada por:

$
A = \left[
\begin{array}{ccccccc}
a & b & 0 & ... & 0 & 0 \\
b & a & b &  0 & \ddots & \vdots \\
0   & b & a & b & \ddots & \vdots \\
\vdots   & \ddots & \ddots & \ddots & \ddots & 0 \\
\vdots   & \ddots & 0 & b & a & b \\
0   & ... & ... & 0 & b & a \\
\end{array}
\right]_{nxn}
$

Faça um algoritmo para obter uma decomposição Cholesky de uma matriz tridiagonal $A_{a,b,n}$, supondo que ela seja definida positiva.

In [81]:
def is_simetric(matrix):
    n = len(matrix)
    for i in range(n):
        for j in range(i,n):
            if i != j :
                if matrix[i][j] != matrix[j][i]:
                    return False
    return True

def is_defined_positive(matrix):
    eigvalues = np.linalg.eigvals(matrix)
    for i in eigvalues:
        if(not np.isreal(i)):
            return False
    return min(eigvalues)>0


def Cholesky_Tridiagonal(A):
    if is_simetric(A) and is_defined_positive(A):
        
        L = copy.deepcopy(A)
        n = len(A)
        for i in range(n-1):
            L[i][i] = L[i][i]**(1/2)
            L[i+1][i] = L[i+1][i]/L[i][i]
            L[i+1][i+1] = L[i+1][i+1] - L[i+1][i]**(2)  
        L[n-1][n-1] = L[n-1][n-1]**(1/2)
        return L
    else:
        return "Não é simétrica ou definida positiva"

In [82]:
A = [[5,1,0,0],[1,5,1,0],[0,1,5,1],[0,0,1,5]]

In [46]:
Cholesky_Tridiagonal(A)

[[2.23606797749979, 1, 0, 0],
 [0.4472135954999579, 2.1908902300206643, 1, 0],
 [0, 0.45643546458763845, 2.188987589427283, 1],
 [0, 0, 0.45683219257612856, 2.188904828407596]]

In [47]:
np.linalg.cholesky(A)

array([[2.23606798, 0.        , 0.        , 0.        ],
       [0.4472136 , 2.19089023, 0.        , 0.        ],
       [0.        , 0.45643546, 2.18898759, 0.        ],
       [0.        , 0.        , 0.45683219, 2.18890483]])

## Questão 1 b.

Faça um algoritmo para obter uma decomposição QR de uma matriz tridiagonal $A_{a,b,n}$. Escolha entre Gram-Schmidt, Householder e Givens, a que melhor se aplica nesse contexto.

In [78]:
def givens(A):
    n = len(A)
    R = copy.deepcopy(A)
    Q = np.identity(n)
    for i in range(n-1):
        a = R[i][i]
        b = R[i+1][i]
        r = np.sqrt(a*a + b*b)
        c = a/r
        s = -b/r
        I = np.identity(n)
        I[i][i] = c
        I[i+1][i] = s
        I[i][i+1] = -s
        I[i+1][i+1] = c
        R = np.dot(I,R)
    return R

In [79]:
R = givens(A)
print("**********  R  ******************")
print(R)

**********  R  ******************
[[5.09901951 1.96116135 0.19611614 0.        ]
 [0.         4.81184436 1.99827424 0.20782052]
 [0.         0.         4.79253988 1.99992443]
 [0.         0.         0.         4.68584175]]


In [80]:
np.linalg.qr(A)[1]

array([[-5.09901951, -1.96116135, -0.19611614,  0.        ],
       [ 0.        , -4.81184436, -1.99827424, -0.20782052],
       [ 0.        ,  0.        , -4.79253988, -1.99992443],
       [ 0.        ,  0.        ,  0.        ,  4.68584175]])

## Questão 3

Determine uma base ortonormal para o espaço complementar ortogonal ao vetor $v = [1,-1,1] \in \mathbb{R}^{3}.$

## Questão 4

Suponha que uma matriz $A \in \mathbb{R}^{mxn}$ tenha posto máximo. A pseudoinversa, ou inversa de Moore-Penrose, de $A$ é a matriz $A^{+} \in \mathbb{R}^{nxm}$ que satisfaz:

<ul>
  <li>$AA^{+}A = A$</li>
  <li>$A^{+}AA^{+} = A^{+}$</li>
  <li>$(AA^{+})^{T} = AA^{+}$</li>
  <li>$(A^{+}A)^{T} = A^{+}A$</li>
</ul>

Calcule a pseudoinversa de

In [6]:
def VerifyProperties(A):
    A_pseudo = Pseudoinverse(A)
    cond1 = np.dot(np.dot(A,A_pseudo),A)                # AA+A  == A 
    cond2 = np.dot(np.dot(A_pseudo,A),A_pseudo)         # A+AA+ == A+
    
    aux = np.dot(A,A_pseudo)                            # (AA+) == AA+ 
    cond3 = aux.T
    
    aux2 = np.dot(A_pseudo,A)
    cond4 = aux2.T                                      # (A+A) == A+A
    
    if np.matrix.all(cond1 == A) and np.matrix.all(cond2 == A_pseudo) and np.matrix.all(cond3 == np.dot(A,A_pseudo)) and np.matrix.all(cond4 == np.dot(A_pseudo,A)):
            return True
    else:
        return False

In [5]:
def Pseudoinverse(A):
    return np.dot(inv(np.dot(A.T,A)),A.T)
    
    
A = np.matrix([[1,0],[0,1],[0,1]])
B = np.matrix([[2,-1,0],[4,3,-2]])
print(Pseudoinverse(B))

[[ 0.125  0.5  ]
 [-0.75   0.   ]
 [-1.     0.   ]]


In [7]:
VerifyProperties(B)

False

In [8]:
a = np.matrix([[True,False],[True,True],[True,True]])