### João Vitor Chaves de Oliveira <br>
### Professor Hélio Côrtes Vieira Lopes

In [1]:
import numpy as np
from numpy.linalg import inv
import copy as copy
np.set_printoptions(suppress=True)
import math

## Questão 1 a.

Seja $A_{a,b,n} \in \mathbb{R}^{nxn}$ a matriz tridiagonal dada por:

$
A = \left[
\begin{array}{ccccccc}
a & b & 0 & ... & 0 & 0 \\
b & a & b &  0 & \ddots & \vdots \\
0   & b & a & b & \ddots & \vdots \\
\vdots   & \ddots & \ddots & \ddots & \ddots & 0 \\
\vdots   & \ddots & 0 & b & a & b \\
0   & ... & ... & 0 & b & a \\
\end{array}
\right]_{nxn}
$

Faça um algoritmo para obter uma decomposição Cholesky de uma matriz tridiagonal $A_{a,b,n}$, supondo que ela seja definida positiva.

In [2]:
def is_simetric(matrix):
    n = len(matrix)
    for i in range(n):
        for j in range(i,n):
            if i != j :
                if matrix[i][j] != matrix[j][i]:
                    return False
    return True

def is_defined_positive(matrix):
    eigvalues = np.linalg.eigvals(matrix)
    for i in eigvalues:
        if(not np.isreal(i)):
            return False
    return min(eigvalues)>0


def Cholesky_Tridiagonal(A):
    if is_simetric(A) and is_defined_positive(A):
        L = copy.deepcopy(A)
        n = len(A)
        for i in range(n-1):
            L[i][i] = L[i][i]**(1/2)
            L[i+1][i] = L[i+1][i]/L[i][i]
            L[i+1][i+1] = L[i+1][i+1] - L[i+1][i]**(2)  
        L[n-1][n-1] = L[n-1][n-1]**(1/2)
        
        for i in range(n):
            for j in range(i+1,n):
                L[i][j] = 0
        return L
    else:
        return "Não é simétrica ou não é definida positiva"

### Exemplos

In [3]:
A = [[5,1,0,0],[1,5,1,0],[0,1,5,1],[0,0,1,5]]

In [4]:
r = np.array(Cholesky_Tridiagonal(A))
r

array([[2.23606798, 0.        , 0.        , 0.        ],
       [0.4472136 , 2.19089023, 0.        , 0.        ],
       [0.        , 0.45643546, 2.18898759, 0.        ],
       [0.        , 0.        , 0.45683219, 2.18890483]])

In [5]:
np.linalg.cholesky(A)

array([[2.23606798, 0.        , 0.        , 0.        ],
       [0.4472136 , 2.19089023, 0.        , 0.        ],
       [0.        , 0.45643546, 2.18898759, 0.        ],
       [0.        , 0.        , 0.45683219, 2.18890483]])

In [6]:
np.dot(r,r.T)

array([[5., 1., 0., 0.],
       [1., 5., 1., 0.],
       [0., 1., 5., 1.],
       [0., 0., 1., 5.]])

In [7]:
B = [[2, 1,0,0,0], [1,2,1,0,0], [0,1,2,1,0],[0,0,1,2,1],[0,0,0,1,2]]

In [8]:
r1 = np.array(Cholesky_Tridiagonal(B))
r1

array([[1.41421356, 0.        , 0.        , 0.        , 0.        ],
       [0.70710678, 1.22474487, 0.        , 0.        , 0.        ],
       [0.        , 0.81649658, 1.15470054, 0.        , 0.        ],
       [0.        , 0.        , 0.8660254 , 1.11803399, 0.        ],
       [0.        , 0.        , 0.        , 0.89442719, 1.09544512]])

In [9]:
np.linalg.cholesky(B)

array([[1.41421356, 0.        , 0.        , 0.        , 0.        ],
       [0.70710678, 1.22474487, 0.        , 0.        , 0.        ],
       [0.        , 0.81649658, 1.15470054, 0.        , 0.        ],
       [0.        , 0.        , 0.8660254 , 1.11803399, 0.        ],
       [0.        , 0.        , 0.        , 0.89442719, 1.09544512]])

In [10]:
np.dot(r1,r1.T)

array([[2., 1., 0., 0., 0.],
       [1., 2., 1., 0., 0.],
       [0., 1., 2., 1., 0.],
       [0., 0., 1., 2., 1.],
       [0., 0., 0., 1., 2.]])

## Questão 1 b.

Faça um algoritmo para obter uma decomposição QR de uma matriz tridiagonal $A_{a,b,n}$. Escolha entre Gram-Schmidt, Householder e Givens, a que melhor se aplica nesse contexto.

In [11]:
def givens(A):
    k = 0
    n = len(A)
    R = copy.deepcopy(A)
    Q = np.identity(n)
    for i in range(n-1):
        a = R[i][i]
        b = R[i+1][i]
        r = np.sqrt(np.power(a,2) + np.power(b,2))
        c = a/float(r)
        s = -b/float(r)
        Qk = np.identity(n)
        Qk[i][i] = c
        Qk[i+1][i] = s
        Qk[i][i+1] = -s
        Qk[i+1][i+1] = c
        if(k==0):
            k=1
            Q = Qk
            R = np.matmul(Qk,R)
        else:
            
            Q = np.matmul(Qk,Q)
            R = np.matmul(Qk,R)
    return R,Q.T

In [12]:
# Matriz B = [[2, 1,0,0,0], [1,2,1,0,0], [0,1,2,1,0],[0,0,1,2,1],[0,0,0,1,2]]
R,Q = givens(B)
print("**********  R  ******************")
print(R)
print("**********  Q  ******************")
print(Q)
print("**********  QR  ******************")
print(np.dot(Q,R))

**********  R  ******************
[[ 2.23606798  1.78885438  0.4472136   0.          0.        ]
 [ 0.          1.67332005  1.91236577  0.5976143   0.        ]
 [ 0.          0.          1.46385011  1.95180015  0.68313005]
 [ 0.         -0.          0.          1.3540064   1.96946386]
 [ 0.          0.         -0.          0.          0.80903983]]
**********  Q  ******************
[[ 0.89442719 -0.35856858  0.19518001 -0.12309149  0.13483997]
 [ 0.4472136   0.71713717 -0.39036003  0.24618298 -0.26967994]
 [ 0.          0.5976143   0.58554004 -0.36927447  0.40451992]
 [ 0.          0.          0.68313005  0.49236596 -0.53935989]
 [ 0.          0.          0.          0.73854895  0.67419986]]
**********  QR  ******************
[[ 2.  1. -0.  0.  0.]
 [ 1.  2.  1. -0. -0.]
 [ 0.  1.  2.  1.  0.]
 [ 0.  0.  1.  2.  1.]
 [ 0.  0. -0.  1.  2.]]


## Questão 3

Determine uma base ortonormal para o espaço complementar ortogonal ao vetor $v = [1,-1,1] \in \mathbb{R}^{3}.$

In [13]:
def show(v):
    k = 1
    for i in v:
        print("Norma do vetor w{} : {}".format(k,np.linalg.norm(i)))
        print("")
        k+=1

def norma(v):
    return np.sqrt(v[0]**2+v[1]**2+v[2]**2)

    
def ComplementoOrtonormal(v):
    x,y,z = v

    if x == 0 and y == 0 and z == 0:
        return [1,0,0],[0,1,0],[0,0,1]
    
    elif x != 0:
        v1 = np.array([-z/x,0,1])
        v2 = np.array([-y/x,1,0])
        w1 = v1
        w1v2 = np.dot(w1,v2)
        w1w1 = (w1[0]**2+w1[1]**2+w1[2]**2)
        w2 = v2 - (w1v2/w1w1)*w1
    
        nw1 = np.linalg.norm(w1)
        nw2 = np.linalg.norm(w2)
        return w1/nw1,w2/nw2
        
    
    elif y !=0:
        v1 = np.array([1,-x/y,0])
        v2 = np.array([0,-z/y,1])
        w1 = v1
        w1v2 = np.dot(w1,v2)
        w1w1 = (w1[0]**2+w1[1]**2+w1[2]**2)
        w2 = v2 - (w1v2/w1w1)*w1
    
        nw1 = np.linalg.norm(w1)
        nw2 = np.linalg.norm(w2)
        return w1/nw1,w2/nw2
        
        
    elif z != 0:
        v1 = np.array([1,0,x/z])
        v2 = np.array([0,1,-y/z])
        w1 = v1
        w1v2 = np.dot(w1,v2)
        w1w1 = (w1[0]**2+w1[1]**2+w1[2]**2)
        w2 = v2 - (w1v2/w1w1)*w1
    
        nw1 = np.linalg.norm(w1)
        nw2 = np.linalg.norm(w2)
        return w1/norma(w1),w2/norma(w2)


In [14]:
v = np.array([1,-1,1])
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])
v3 = np.array([0,0,1])
v4 = np.array([0,0,0])

Questão descrita na prova:

In [15]:
print("Complemento: {} \n".format(ComplementoOrtonormal(v)))
show(ComplementoOrtonormal(v))

Complemento: (array([-0.70710678,  0.        ,  0.70710678]), array([0.40824829, 0.81649658, 0.40824829])) 

Norma do vetor w1 : 0.9999999999999999

Norma do vetor w2 : 1.0



Outros exemplos:

In [16]:
print("Complemento: {} \n".format(ComplementoOrtonormal(v1)))
show(ComplementoOrtonormal(v1))

Complemento: (array([0., 0., 1.]), array([0., 1., 0.])) 

Norma do vetor w1 : 1.0

Norma do vetor w2 : 1.0



In [17]:
print("Complemento: {} \n".format(ComplementoOrtonormal(v2)))
show(ComplementoOrtonormal(v2))

Complemento: (array([1., 0., 0.]), array([0., 0., 1.])) 

Norma do vetor w1 : 1.0

Norma do vetor w2 : 1.0



In [18]:
print("Complemento: {} \n".format(ComplementoOrtonormal(v3)))
show(ComplementoOrtonormal(v3))

Complemento: (array([1., 0., 0.]), array([0., 1., 0.])) 

Norma do vetor w1 : 1.0

Norma do vetor w2 : 1.0



In [19]:
print("Complemento: {} \n".format(ComplementoOrtonormal(v4)))
show(ComplementoOrtonormal(v4))

Complemento: ([1, 0, 0], [0, 1, 0], [0, 0, 1]) 

Norma do vetor w1 : 1.0

Norma do vetor w2 : 1.0

Norma do vetor w3 : 1.0



## Questão 4

Calcule a pseudoinversa de

$
A = \left[
\begin{array}{cc}
1 & 0 \\
0 & 1 \\
0 & 1\\
\end{array}
\right]
$

In [155]:
def Pseudoinverse(A):
    At = np.transpose(A)
    AtA = np.dot(At,A)
    AtA_inv = np.linalg.inv(AtA)
    Pi = np.dot(AtA_inv,At)
    return Pi

In [186]:
#A+ = (ATA)-1(AT)

def Propriedade1(A,A_p): #AA+A = A
    AA_pA = np.dot(np.dot(A,A_p),A)
    print(AA_pA)
    print("")
    print(A)
    
def Propriedade2(A,A_p): #A+AA+ A+
    A_pAA_p = np.dot(np.dot(A_p,A),A_p)
    print(A_pAA_p)
    print("")
    print(A_p)
    
def Propriedade3(A,A_p): #(AA+)T = AA+
    AA_pT = np.transpose(np.dot(A,A_p))
    AA_p = np.dot(A,A_p)
    print(AA_pT)
    print("")
    print(AA_p)
    
def Propriedade4(A,A_p): #(A+A)T = A+A
    A_pAT = np.transpose(np.dot(A_p,A))
    A_pA = np.dot(A_p,A)
    print(A_pAT)
    print("")
    print(A_pA)
    

Questão da prova

In [187]:
D = np.matrix([[1,0],[0,1],[0,1]])

In [188]:
PseudoD = Pseudoinverse(D)
print(PseudoD)

[[1.  0.  0. ]
 [0.  0.5 0.5]]


In [189]:
print(np.linalg.pinv(D))

[[1.  0.  0. ]
 [0.  0.5 0.5]]


In [190]:
Propriedade1(D,PseudoD)

[[1. 0.]
 [0. 1.]
 [0. 1.]]

[[1 0]
 [0 1]
 [0 1]]


In [191]:
Propriedade2(D,PseudoD)

[[1.  0.  0. ]
 [0.  0.5 0.5]]

[[1.  0.  0. ]
 [0.  0.5 0.5]]


In [192]:
Propriedade3(D,PseudoD)

[[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]

[[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]


In [193]:
Propriedade4(D,PseudoD)

[[1. 0.]
 [0. 1.]]

[[1. 0.]
 [0. 1.]]


Outro exemplo:

In [179]:
C = np.matrix([[7,2],[3,4],[5,3]])
C.astype(float)
print(C)

[[7 2]
 [3 4]
 [5 3]]


In [180]:
PseudoC = Pseudoinverse(C)
print(PseudoC)

[[ 0.16666667 -0.10606061  0.03030303]
 [-0.16666667  0.28787879  0.06060606]]


In [181]:
print(np.linalg.pinv(C))

[[ 0.16666667 -0.10606061  0.03030303]
 [-0.16666667  0.28787879  0.06060606]]


In [182]:
Propriedade1(C,PseudoC)

[[7. 2.]
 [3. 4.]
 [5. 3.]]

[[7 2]
 [3 4]
 [5 3]]


In [183]:
Propriedade2(C,PseudoC)

[[ 0.16666667 -0.10606061  0.03030303]
 [-0.16666667  0.28787879  0.06060606]]

[[ 0.16666667 -0.10606061  0.03030303]
 [-0.16666667  0.28787879  0.06060606]]


In [184]:
Propriedade3(C,PseudoC)

[[ 0.83333333 -0.16666667  0.33333333]
 [-0.16666667  0.83333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]]

[[ 0.83333333 -0.16666667  0.33333333]
 [-0.16666667  0.83333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]]


In [185]:
Propriedade4(C,PseudoC)

[[ 1.  0.]
 [-0.  1.]]
[[ 1. -0.]
 [ 0.  1.]]
